CREATE DATABASE IF NOT EXISTS optwitter;
CREATE DATABASE IF NOT EXISTS optomo;

DROP TABLE IF EXISTS optwitter.users;
CREATE TABLE optwitter.users (
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(20) UNIQUE,
    salt VARCHAR(20),
    password VARCHAR(40)
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS optwitter.tweets;
CREATE TABLE optwitter.tweets (
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    user_id BIGINT UNSIGNED,
    text TEXT,
    created_at DATETIME NOT NULL
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS optomo.friends;
CREATE TABLE optomo.friends (
    id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    me VARCHAR(20) UNIQUE,
    friends TEXT
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;
